config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root "application#hello"
  root "pages#home"
  get'/about', to: 'pages#about'
  get'/help', to: 'pages#help'
  delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
  get '/articles/:id/delete' => 'articles#destroy'
  resources :todos
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  belongs_to :user
end

app/models/user.rb
class user < ApplicationRecord
   has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def hello
      render plain:"hello world !"
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  def about
  end
  def help
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  def new
    @todo =Todo.new
  end

  def create
    @todo=Todo.new(todo_params)
    if @todo.save
      flash[:notice]="Todo is created"
      redirect_to todo_path(@todo)
    else
      render 'new', status: 422
    end

  end

  def show

  end

  def edit

  end
  def update

     if @todo.update(todo_params)
       flash[:notice]="Todo was updated"
       redirect_to todo_path(@todo)
     else
      render'edit',status: 422
     end
  end
  def index
    @todos=Todo.all
  end
  def destroy

    @todo.destroy
    flash[:notice]="Todo was deleted"
    redirect_to todos_path
  end
  private
    def set_todo
      @todo=Todo.find(params[:id])
    end
    def todo_params
      params.require(:todo).permit(:name, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/pages/help.html.erb
<h1>In help page</h1>

app/views/pages/home.html.erb
<h1>hello World</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
    <h1>The following errors preventing to run</h1>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @todo do |f| %>
    <p>
        <%=f.label :name %><br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%=f.label :description %><br>
        <%=f.text_area :description%>
    </p>
    <p>
        <%=f.submit %>
    </p>

<% end %>

app/views/todos/edit.html.erb
<h1>editing todo</h1>
<%= render 'form' %>
<%=link_to "Back to todos listing", todos_path%>

app/views/todos/index.html.erb
<h1>Listing Todos</h1>
<p>
    <%=link_to "Create a Todo" , new_todo_path%>
</p>
<table>
    <tr>
        <th>Name </th>
        <th>Description </th>
    </tr>
    <% @todos.each do |todo| %>
        <tr>
            <td><%=todo.name%> </td>
            <td><%=todo.description%></td>
            <td><%= link_to "Edit",edit_todo_path(todo)%></td>
            <td><%= link_to "Show",todo_path(todo)%> </td>
            <td><%= link_to 'Delete',todo_path(todo), data: { turbo: true, turbo_method: :delete }, :onclick => "return confirm('Are you sure you want to delete this post?')" %></td>
            <td></td>
        </tr>
    <%end%>
</table>

app/views/todos/new.html.erb
<h1>Todo page</h1>
<%= render 'form' %>
<%= link_to "Back to todos listing", todos_path%>

app/views/todos/show.html.erb
<h1>Showing a todo</h1>
<p>
    name: <%=@todo.name %>
</p>
<p>
    description: <%= @todo.description %>
</p>
<%= link_to "Edit this todo", edit_todo_path(@todo)%> |
<%= link_to "Back to todos listing", todos_path %>